title: "Riot.js で Tour of Heroes を試す"
summary: |-

  Riot.js のチュートリアル用の書籍です．Google 社謹製の JavaScript フレームワーク Angular のチュートリアル「Tour of Heroes」 を Riot.js で通してみるものです！

  https://angular.io/tutorial

  完成版のソースコードは GitHub にアップしておりますので，何かわからないことがあればこちらのコードを参考にしていただければと思いますー．

  https://github.com/kkeeth/riot-toh-demo

topics: ["riotjs", "ToH", "tutorial"]
published: public
price: 0 # 有料の場合200〜5000
chapters:
  - environment
  - hero_component
  - show_list
  - hero_detail
  - services
  - dashboard
  - remote_server
  - unit_test
  - using_vite
