title: "JavaScript でテトリスを作ろう"
summary: |-

  JavaScript と HTML5 Canvasを使用して，シンプルなテトリスゲームを作成します．
  このチュートリアルでは，基本的なゲームロジック，描画，ユーザーインターフェースの実装方法を学びます．

  学生へのプログラミングの講師（主に `JavaScript`） を数年経験してきましたが，毎度困っているのが「何を作るか」です．

  * 新年までのカウントダウン
  * 個人ホームページ
  * ブログ
  * ToDo アプリ

  等々，色々作ってきましたが，今回は今まで作ったことがない「テトリス」を作ってみました！

  なんでテトリス？インターネットで何度か噂や記事を見たことがあって，これを機にやってみようかなーと思って，ご存知 ChatGPT 4o 君と一緒に 作ってみたので，books にまとめてみました．ご参考になれば幸いです！

topics: ["JavaScript", "テトリス", "入門書"]
published: true
price: 0
chapters:
  - preparation
  - create_pieces
  - game_logic
  - update_render_game
  - user_interface